inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - gemfiles/**/*
  TargetRubyVersion: 2.4
  NewCops: enable


################
# Layout Rules #
################
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/LineLength:
  Max: 140

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space


################
# Code Metrics #
################
Metrics/BlockLength:
  Exclude:
    - 'test/schema.rb'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 10
  CountComments: false


###############
# Style Rules #
###############
Style/Alias:
  EnforcedStyle: prefer_alias_method

# ¯\_(ツ)_/¯
# ʕノ•ᴥ•ʔノ ︵ ┻━┻
# ( ͡° ͜ʖ ͡°)
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
